language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0snapshot

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source --no-interaction

script: vendor/bin/phpunit --verbose
